[2024-12-06T15:13:18.365+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T15:13:18.380+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_cleaned_data.generate_insert_sql manual__2024-12-06T14:53:18.041571+00:00 [queued]>
[2024-12-06T15:13:18.387+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_cleaned_data.generate_insert_sql manual__2024-12-06T14:53:18.041571+00:00 [queued]>
[2024-12-06T15:13:18.388+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2024-12-06T15:13:18.401+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_insert_sql> on 2024-12-06 14:53:18.041571+00:00
[2024-12-06T15:13:18.407+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2697) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-06T15:13:18.408+0000] {standard_task_runner.py:72} INFO - Started process 2698 to run task
[2024-12-06T15:13:18.408+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'insert_cleaned_data', 'generate_insert_sql', 'manual__2024-12-06T14:53:18.041571+00:00', '--job-id', '1993', '--raw', '--subdir', 'DAGS_FOLDER/insert_cleaned_data.py', '--cfg-path', '/tmp/tmpp0e41wcl']
[2024-12-06T15:13:18.409+0000] {standard_task_runner.py:105} INFO - Job 1993: Subtask generate_insert_sql
[2024-12-06T15:13:18.440+0000] {task_command.py:467} INFO - Running <TaskInstance: insert_cleaned_data.generate_insert_sql manual__2024-12-06T14:53:18.041571+00:00 [running]> on host cb0074367deb
[2024-12-06T15:13:18.492+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='artzsh' AIRFLOW_CTX_DAG_ID='insert_cleaned_data' AIRFLOW_CTX_TASK_ID='generate_insert_sql' AIRFLOW_CTX_EXECUTION_DATE='2024-12-06T14:53:18.041571+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-06T14:53:18.041571+00:00'
[2024-12-06T15:13:18.493+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T15:13:18.513+0000] {insert_cleaned_data.py:50} INFO - Ключ 'None' не найден в tables_json. Завершение вставки.
[2024-12-06T15:13:18.523+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-06T15:13:18.529+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T15:13:18.530+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=insert_cleaned_data, task_id=generate_insert_sql, run_id=manual__2024-12-06T14:53:18.041571+00:00, execution_date=20241206T145318, start_date=20241206T151318, end_date=20241206T151318
[2024-12-06T15:13:18.542+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-06T15:13:18.557+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-06T15:13:18.560+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
