[2024-12-05T19:10:42.375+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T19:10:42.386+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_unique_values.create_unique_brands manual__2024-12-05T19:10:40.771516+00:00 [queued]>
[2024-12-05T19:10:42.392+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_unique_values.create_unique_brands manual__2024-12-05T19:10:40.771516+00:00 [queued]>
[2024-12-05T19:10:42.392+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2024-12-05T19:10:42.403+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): create_unique_brands> on 2024-12-05 19:10:40.771516+00:00
[2024-12-05T19:10:42.407+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=896) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-05T19:10:42.408+0000] {standard_task_runner.py:72} INFO - Started process 897 to run task
[2024-12-05T19:10:42.409+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_unique_values', 'create_unique_brands', 'manual__2024-12-05T19:10:40.771516+00:00', '--job-id', '483', '--raw', '--subdir', 'DAGS_FOLDER/select_distinct_brands_categories.py', '--cfg-path', '/tmp/tmp_8howeh7']
[2024-12-05T19:10:42.410+0000] {standard_task_runner.py:105} INFO - Job 483: Subtask create_unique_brands
[2024-12-05T19:10:42.441+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_unique_values.create_unique_brands manual__2024-12-05T19:10:40.771516+00:00 [running]> on host c7780884450d
[2024-12-05T19:10:42.499+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='artzsh' AIRFLOW_CTX_DAG_ID='extract_unique_values' AIRFLOW_CTX_TASK_ID='create_unique_brands' AIRFLOW_CTX_EXECUTION_DATE='2024-12-05T19:10:40.771516+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-05T19:10:40.771516+00:00'
[2024-12-05T19:10:42.499+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T19:10:42.520+0000] {select_distinct_brands_categories.py:50} INFO - Обрабатываем ключ: 2
[2024-12-05T19:10:42.520+0000] {select_distinct_brands_categories.py:65} INFO - Источник брендов: DDS.brands_Nov
[2024-12-05T19:10:42.521+0000] {select_distinct_brands_categories.py:66} INFO - Целевая таблица брендов: DDS.unique_brands
[2024-12-05T19:10:42.526+0000] {base.py:84} INFO - Retrieving connection 'database_cloud'
[2024-12-05T19:10:43.212+0000] {select_distinct_brands_categories.py:87} INFO - Соединение с PostgreSQL установлено.
[2024-12-05T19:10:43.497+0000] {select_distinct_brands_categories.py:100} INFO - Целевая таблица 'DDS.unique_brands' создана или уже существует.
[2024-12-05T19:10:43.685+0000] {select_distinct_brands_categories.py:111} INFO - Количество уникальных брендов в источнике: 1987
[2024-12-05T19:10:43.774+0000] {select_distinct_brands_categories.py:122} INFO - Количество брендов в целевой таблице до вставки: 1731
[2024-12-05T19:10:43.867+0000] {select_distinct_brands_categories.py:154} ERROR - Ошибка при добавлении брендов: there is no unique or exclusion constraint matching the ON CONFLICT specification

[2024-12-05T19:10:43.961+0000] {select_distinct_brands_categories.py:161} INFO - Курсор закрыт.
[2024-12-05T19:10:43.962+0000] {select_distinct_brands_categories.py:164} INFO - Соединение с PostgreSQL закрыто.
[2024-12-05T19:10:43.963+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/select_distinct_brands_categories.py", line 137, in create_unique_brands
    cursor.execute(insert_query)
psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification

[2024-12-05T19:10:43.976+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_unique_values, task_id=create_unique_brands, run_id=manual__2024-12-05T19:10:40.771516+00:00, execution_date=20241205T191040, start_date=20241205T191042, end_date=20241205T191043
[2024-12-05T19:10:43.990+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T19:10:43.990+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 483 for task create_unique_brands (there is no unique or exclusion constraint matching the ON CONFLICT specification
; 897)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/select_distinct_brands_categories.py", line 137, in create_unique_brands
    cursor.execute(insert_query)
psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification

[2024-12-05T19:10:44.027+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-05T19:10:44.042+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T19:10:44.046+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
